In [3]:
# Jupyter 参数设置
# 导入设置后， 在一个cell 可以输出多个值
# 就没有必要用不同的cell去运行
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
import time


## Numpy生成数组对象 ndarray，一维或者多维数组对象
创建数组对象

In [24]:
tmp_array = np.array([1,2,3])
tmp_array


tmp2_array = np.array([[1,2,3],[4,5,6]])
tmp2_array

# 改变数据类型
tmp3_array = np.array([1,2,3], dtype = np.float64)
tmp3_array


array([1, 2, 3])

array([[1, 2, 3],
       [4, 5, 6]])

array([1., 2., 3.])

***Numpy*** 计算速度是十分快的！！！  
在100万数量级上测试十个循环，时间差了大概40倍！！！

In [44]:
test_arr = np.arange(1000000)
test_list = list(range(1000000))

%time for _ in range(10): result  = test_arr * 2
%time for _ in range(10): [x * 2 for x in test_list]

CPU times: user 13.8 ms, sys: 3.92 ms, total: 17.7 ms
Wall time: 17.8 ms
CPU times: user 637 ms, sys: 173 ms, total: 809 ms
Wall time: 822 ms


创建随机数, 0数组

In [4]:
random_tmp = np.random.randn(2, 3)
random_tmp


array([[1.47593882, 0.50905093, 1.3576141 ],
       [0.07974237, 1.06984986, 0.1807174 ]])

In [39]:
zeros_tmp = np.zeros(3)
zeros_tmp

zeros_tmp2 = np.zeros((2, 3), dtype = np.int64)
zeros_tmp2

array([0., 0., 0.])

array([[0, 0, 0],
       [0, 0, 0]])

数组的一些运算

In [5]:
random_tmp + random_tmp
random_tmp * random_tmp
random_tmp - random_tmp
1 / random_tmp
random_tmp ** 2

array([[2.95187764, 1.01810186, 2.71522819],
       [0.15948475, 2.13969972, 0.36143479]])

array([[2.17839541, 0.25913285, 1.84311604],
       [0.00635885, 1.14457872, 0.03265878]])

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[ 0.67753486,  1.96443999,  0.73658634],
       [12.54038435,  0.9347106 ,  5.5335016 ]])

array([[2.17839541, 0.25913285, 1.84311604],
       [0.00635885, 1.14457872, 0.03265878]])

### 索引和切片操作

In [127]:
tmp_data = np.arange(10).reshape(2, 5)
tmp_data

tmp_data[1]

tmp_data.T
tmp_data.T[0]

tmp_data[:, 0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([5, 6, 7, 8, 9])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

array([0, 5])

array([0, 5])

***在拷贝这里要注意一个事情，浅拷贝，深拷贝***


In [65]:
a = np.arange(3)
print(a)

b = a 
b[0] =10086

print(b)
print(a)

# 改变b的值后，a的值会改变
# 可以把b当作为a的快捷方式（不同指针是指向同一内存的）

[0 1 2]
[10086     1     2]
[10086     1     2]


In [66]:
a = np.arange(3)
print(a)

b = a.copy()
b[0] =10086


print(b)
print(a)
# copy之后，改变b的值后，a的值不会改变

[0 1 2]
[10086     1     2]
[0 1 2]


拓展一下，浅拷贝和深拷贝的区别`copy()` 和 `deepcopy()` 的区别

In [110]:
a = [1,2,[3,4]]
b = a.copy()
b[0] =10086
print(b)
print(a)
# 1 和 [3,4] 是属于同一层数据，

b[2][1] = 9999
print(b)
print(a)
# 浅拷贝里面的嵌套数据还是指向同一内存！！！

[10086, 2, [3, 4]]
[1, 2, [3, 4]]
[10086, 2, [3, 9999]]
[1, 2, [3, 9999]]


In [109]:
from copy import deepcopy
a = [1,2, [3,4]]
b = deepcopy(a)

b[2][1] = 99999
print(a)
print(b)
# 深拷贝里面的嵌套数据，是指向不同的内存的！！！

[1, 2, [3, 4]]
[1, 2, [3, 99999]]


如果数据里面没有再嵌套一层数据，则深拷贝浅拷贝作用是一样的。  
但是如果数据里面有嵌套数据，则深拷贝，浅拷贝作用是不一样的。比如说上面的 `1`,`2`,`[3,4]`，对于第一层的数据 , b中修改第一层数据`1`,`2`,`[3,4]` ，b的改变不对a有影响。

但如果改变b中第一层数据的嵌套数据`[3,4]` 中的 `3`或`4`（上面例子，改变`4`为`99999`), 对于浅拷贝，a中的嵌套数据里面的数据也会跟着变化。 

但对于深拷贝，b嵌套数据里面的数据改变后，a中但嵌套数据里面的数据不会发生任何改变


### 布尔型索引

In [136]:
name = np.array(['xiao', 'zhi', 'qian', 'xiao'])
tmp_data = np.random.randn(4,6)
tmp_data

# 选取了name == 'xiao' 的行
tmp_data[name == 'xiao']

tmp_data[name == 'xiao', 2:5]


array([[ 0.50141269, -0.42452748,  0.20110261,  1.50819879, -0.95307112,
         0.5799029 ],
       [ 2.12486682,  1.38709778, -1.10219046,  0.68203119, -0.49276069,
        -1.29582998],
       [ 0.3573493 , -1.88432254, -2.20779592,  1.8646964 , -1.98913561,
        -0.48809546],
       [-0.45846506,  1.35765929, -1.75265356, -0.15750285, -0.28162653,
         1.91665576]])

array([[ 0.50141269, -0.42452748,  0.20110261,  1.50819879, -0.95307112,
         0.5799029 ],
       [-0.45846506,  1.35765929, -1.75265356, -0.15750285, -0.28162653,
         1.91665576]])

array([[ 0.20110261,  1.50819879, -0.95307112],
       [-1.75265356, -0.15750285, -0.28162653]])

In [146]:
tmp_data[tmp_data<0] = 0 # 将小于0的值设定为0
tmp_data

array([[0.50141269, 0.        , 0.20110261, 1.50819879, 0.        ,
        0.5799029 ],
       [2.12486682, 1.38709778, 0.        , 0.68203119, 0.        ,
        0.        ],
       [0.3573493 , 0.        , 0.        , 1.8646964 , 0.        ,
        0.        ],
       [0.        , 1.35765929, 0.        , 0.        , 0.        ,
        1.91665576]])

### 花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [8]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [14]:
arr[[4,3,7]]
# 选取其中第四行，第三行，第七行


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [19]:
arr.T
arr.T[[1,2]]

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

## 线性代数的一些计算方法 

In [35]:
x = np.arange(9).reshape(3,3)
y = np.arange(6).reshape(3,2)
x
y
x.dot(y)
np.dot(x,y)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[10, 13],
       [28, 40],
       [46, 67]])

array([[10, 13],
       [28, 40],
       [46, 67]])

In [36]:
np.dot(x, np.ones(3))

array([ 3., 12., 21.])

In [61]:
from numpy.linalg import inv, qr

X = np.random.randn(3,3)
X

mat = X.T.dot(X) # X 乘 X.T 结果必为实对称矩阵，实对称矩阵必可对角化
mat # 实对称矩阵



array([[-1.13182776,  0.06898705, -2.0799301 ],
       [-0.40535183,  1.1368754 , -1.19074015],
       [-0.10796796,  0.33165684,  2.40545543]])

array([[ 1.45700126, -0.5747243 ,  2.5770792 ],
       [-0.5747243 ,  1.40724114, -0.69942568],
       [ 2.5770792 , -0.69942568, 11.53018716]])

In [62]:
inv(mat) # mat 的逆矩阵

mat.dot(inv(mat)).astype(int) # 

array([[ 1.32847723,  0.40725834, -0.2722197 ],
       [ 0.40725834,  0.85754996, -0.03900583],
       [-0.2722197 , -0.03900583,  0.1452058 ]])

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
q, r = qr(mat) # QR 分解

In [69]:
q
r

array([[-0.48313729,  0.01819925, -0.87535544],
       [ 0.19057687, -0.97362635, -0.12542798],
       [-0.85455182, -0.22742144,  0.46692685]])

array([[ -3.01570853,   1.14355385, -11.23151984],
       [  0.        ,  -1.22152222,  -1.89433154],
       [  0.        ,   0.        ,   3.21562119]])